name: daily welcome

on:
   #schedule:
   #   - cron: '0 22 * * 1-5'
   #   - cron: '30 23 * * 0,6'
   push:
      branches:
         - feature-action-bsstayo

jobs:
   Login-Welcome:
      name: Login Welcome
      runs-on: ubuntu-latest

      steps:
         - name: Checkout repository
           uses: actions/checkout@v3

         - name: Setup Python
           uses: actions/setup-python@v4
           with:
              python-version: '3.10'

         - name: Run Python File
           run: python ./login_welcome/welcome.py
