name: daily welcome

on:
   schedule:
      - cron: '0 22 * * 1-5'
      - cron: '30 23 * * 0,6'
   #push:
   #   branches:
   #      - feature-action-bsstayo

jobs:
   Login-Welcome:
      name: Login Welcome
      runs-on: ubuntu-latest
      defaults:
         run:
            working-directory: ./login_welcome

      steps:
         - name: Checkout repository
           uses: actions/checkout@v3

         - name: Setup Python
           uses: actions/setup-python@v4
           with:
              python-version: '3.10'

         - name: Install dependencies
           run: |
              python -m pip install --upgrade pip
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

         - name: Run Python File
           run: python welcome.py
